// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/inventory/inventory_service.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_inventory_inventory_service_proto protoreflect.FileDescriptor

const file_proto_inventory_inventory_service_proto_rawDesc = "" +
	"\n" +
	"'proto/inventory/inventory_service.proto\x12\tinventory\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fproto/inventory/inventory.proto2Q\n" +
	"\x10InventoryService\x12=\n" +
	"\rSaveInventory\x12\x14.inventory.Inventory\x1a\x16.google.protobuf.EmptyB/Z-github.com/meokg456/ecommerce/proto/inventoryb\x06proto3"

var file_proto_inventory_inventory_service_proto_goTypes = []any{
	(*Inventory)(nil),     // 0: inventory.Inventory
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_proto_inventory_inventory_service_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.SaveInventory:input_type -> inventory.Inventory
	1, // 1: inventory.InventoryService.SaveInventory:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_inventory_service_proto_init() }
func file_proto_inventory_inventory_service_proto_init() {
	if File_proto_inventory_inventory_service_proto != nil {
		return
	}
	file_proto_inventory_inventory_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_inventory_service_proto_rawDesc), len(file_proto_inventory_inventory_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_inventory_service_proto_goTypes,
		DependencyIndexes: file_proto_inventory_inventory_service_proto_depIdxs,
	}.Build()
	File_proto_inventory_inventory_service_proto = out.File
	file_proto_inventory_inventory_service_proto_goTypes = nil
	file_proto_inventory_inventory_service_proto_depIdxs = nil
}
