// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: product/product_service.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_product_product_service_proto protoreflect.FileDescriptor

const file_product_product_service_proto_rawDesc = "" +
	"\n" +
	"\x1dproduct/product_service.proto\x1a\x15product/product.proto22\n" +
	"\x0eProductService\x12 \n" +
	"\n" +
	"AddProduct\x12\b.Product\x1a\b.ProductB\vZ\t./productb\x06proto3"

var file_product_product_service_proto_goTypes = []any{
	(*Product)(nil), // 0: Product
}
var file_product_product_service_proto_depIdxs = []int32{
	0, // 0: ProductService.AddProduct:input_type -> Product
	0, // 1: ProductService.AddProduct:output_type -> Product
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_product_service_proto_init() }
func file_product_product_service_proto_init() {
	if File_product_product_service_proto != nil {
		return
	}
	file_product_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_product_service_proto_rawDesc), len(file_product_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_product_service_proto_goTypes,
		DependencyIndexes: file_product_product_service_proto_depIdxs,
	}.Build()
	File_product_product_service_proto = out.File
	file_product_product_service_proto_goTypes = nil
	file_product_product_service_proto_depIdxs = nil
}
