// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/product/product_service.proto

package product

import (
	common "github.com/meokg456/ecommerce/proto/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProductsByMerchantIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int64                  `protobuf:"varint,1,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	Page          *common.Page           `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByMerchantIdRequest) Reset() {
	*x = GetProductsByMerchantIdRequest{}
	mi := &file_proto_product_product_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByMerchantIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByMerchantIdRequest) ProtoMessage() {}

func (x *GetProductsByMerchantIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByMerchantIdRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByMerchantIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductsByMerchantIdRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *GetProductsByMerchantIdRequest) GetPage() *common.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetProductsByMerchantIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	LastKey       string                 `protobuf:"bytes,2,opt,name=lastKey,proto3" json:"lastKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByMerchantIdResponse) Reset() {
	*x = GetProductsByMerchantIdResponse{}
	mi := &file_proto_product_product_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByMerchantIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByMerchantIdResponse) ProtoMessage() {}

func (x *GetProductsByMerchantIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByMerchantIdResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByMerchantIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductsByMerchantIdResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *GetProductsByMerchantIdResponse) GetLastKey() string {
	if x != nil {
		return x.LastKey
	}
	return ""
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantId    int64                  `protobuf:"varint,2,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_proto_product_product_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_product_service_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteProductRequest) GetMerchantId() int64 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_proto_product_product_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_product_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_proto_product_product_service_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_product_product_service_proto protoreflect.FileDescriptor

const file_proto_product_product_service_proto_rawDesc = "" +
	"\n" +
	"#proto/product/product_service.proto\x12\aproduct\x1a\x1bproto/product/product.proto\x1a\x19proto/common/common.proto\"b\n" +
	"\x1eGetProductsByMerchantIdRequest\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x01 \x01(\x03R\n" +
	"merchantId\x12 \n" +
	"\x04page\x18\x02 \x01(\v2\f.common.PageR\x04page\"i\n" +
	"\x1fGetProductsByMerchantIdResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x18\n" +
	"\alastKey\x18\x02 \x01(\tR\alastKey\"F\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"merchantId\x18\x02 \x01(\x03R\n" +
	"merchantId\"'\n" +
	"\x15DeleteProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\xb5\x02\n" +
	"\x0eProductService\x12l\n" +
	"\x17GetProductsByMerchantId\x12'.product.GetProductsByMerchantIdRequest\x1a(.product.GetProductsByMerchantIdResponse\x120\n" +
	"\n" +
	"AddProduct\x12\x10.product.Product\x1a\x10.product.Product\x123\n" +
	"\rUpdateProduct\x12\x10.product.Product\x1a\x10.product.Product\x12N\n" +
	"\rDeleteProduct\x12\x1d.product.DeleteProductRequest\x1a\x1e.product.DeleteProductResponseB-Z+github.com/meokg456/ecommerce/proto/productb\x06proto3"

var (
	file_proto_product_product_service_proto_rawDescOnce sync.Once
	file_proto_product_product_service_proto_rawDescData []byte
)

func file_proto_product_product_service_proto_rawDescGZIP() []byte {
	file_proto_product_product_service_proto_rawDescOnce.Do(func() {
		file_proto_product_product_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_product_service_proto_rawDesc), len(file_proto_product_product_service_proto_rawDesc)))
	})
	return file_proto_product_product_service_proto_rawDescData
}

var file_proto_product_product_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_product_product_service_proto_goTypes = []any{
	(*GetProductsByMerchantIdRequest)(nil),  // 0: product.GetProductsByMerchantIdRequest
	(*GetProductsByMerchantIdResponse)(nil), // 1: product.GetProductsByMerchantIdResponse
	(*DeleteProductRequest)(nil),            // 2: product.DeleteProductRequest
	(*DeleteProductResponse)(nil),           // 3: product.DeleteProductResponse
	(*common.Page)(nil),                     // 4: common.Page
	(*Product)(nil),                         // 5: product.Product
}
var file_proto_product_product_service_proto_depIdxs = []int32{
	4, // 0: product.GetProductsByMerchantIdRequest.page:type_name -> common.Page
	5, // 1: product.GetProductsByMerchantIdResponse.products:type_name -> product.Product
	0, // 2: product.ProductService.GetProductsByMerchantId:input_type -> product.GetProductsByMerchantIdRequest
	5, // 3: product.ProductService.AddProduct:input_type -> product.Product
	5, // 4: product.ProductService.UpdateProduct:input_type -> product.Product
	2, // 5: product.ProductService.DeleteProduct:input_type -> product.DeleteProductRequest
	1, // 6: product.ProductService.GetProductsByMerchantId:output_type -> product.GetProductsByMerchantIdResponse
	5, // 7: product.ProductService.AddProduct:output_type -> product.Product
	5, // 8: product.ProductService.UpdateProduct:output_type -> product.Product
	3, // 9: product.ProductService.DeleteProduct:output_type -> product.DeleteProductResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_product_service_proto_init() }
func file_proto_product_product_service_proto_init() {
	if File_proto_product_product_service_proto != nil {
		return
	}
	file_proto_product_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_product_service_proto_rawDesc), len(file_proto_product_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_product_service_proto_goTypes,
		DependencyIndexes: file_proto_product_product_service_proto_depIdxs,
		MessageInfos:      file_proto_product_product_service_proto_msgTypes,
	}.Build()
	File_proto_product_product_service_proto = out.File
	file_proto_product_product_service_proto_goTypes = nil
	file_proto_product_product_service_proto_depIdxs = nil
}
